name = "LearningGridap"
uuid = "138e6656-d2bc-40af-ba54-06edf3ab35ed"
authors = ["Javier Principe"]
version = "1.0.0-DEV"

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"

[compat]
julia = "1.11.1"
